version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chatduck
      POSTGRES_USER: chatduck
      POSTGRES_PASSWORD: chatduck


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: example@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    links:
      - "db:pgsql-server"

  server:
      container_name: chatduck-api
      restart: unless-stopped
      image: chatduck-api-dev:1.0.0
      build:
        context: server
        dockerfile: Dockerfile
      ports:
        - 3001:3001
      depends_on:
        - db
      links:
        - db
      env_file:
        - ./server/.env

  web:
    container_name: chatduck-client
    restart: unless-stopped
    image: chatduck-client:1.0.0
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - server
